spring.application.name=FoodDelivery
spring.profiles.active=local
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
server.port=8080
server.address=0.0.0.0
# Local မှာ ပုံတွေ သိမ်းမည့် Folder Path
file.upload-dir=D:/FoodDelivery/uploads/

# File Size Limit သတ်မှတ်ခြင်း
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB